# Generated by Django 5.1.2 on 2025-06-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoe",
            name="brand",
            field=models.CharField(
                choices=[
                    ("Nike", "Nike"),
                    ("Adidas", "Adidas"),
                    ("Reebok", "Reebok"),
                    ("Converse", "Converse"),
                    ("Puma", "Puma"),
                    ("Jordan", "Jordan"),
                    ("Asics", "Asics"),
                    ("Fila", "Fila"),
                    ("New Balance", "New Balance"),
                    ("Vans", "Vans"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="shoe_type",
            field=models.CharField(
                choices=[
                    ("Basketball", "Basketball"),
                    ("Running", "Running"),
                    ("Casual", "Casual"),
                    ("Lifestyle", "Lifestyle"),
                    ("Accessories", "Accessories"),
                    ("Cross-training", "Cross-training"),
                    ("Crossfit", "Crossfit"),
                    ("Fashion", "Fashion"),
                    ("Racing", "Racing"),
                    ("Retro", "Retro"),
                    ("Skate", "Skate"),
                    ("Slides", "Slides"),
                    ("Trail", "Trail"),
                    ("Trail Running", "Trail Running"),
                    ("Training", "Training"),
                    ("Weightlifting", "Weightlifting"),
                ],
                max_length=100,
            ),
        ),
    ]
