# Generated by Django 5.1.2 on 2024-10-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shoe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("Nike", "Nike"),
                            ("Adidas", "Adidas"),
                            ("Reebok", "Reebok"),
                            ("Converse", "Converse"),
                            ("Puma", "Puma"),
                            ("Jordan", "Jordan"),
                        ],
                        max_length=100,
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "shoe_type",
                    models.CharField(
                        choices=[
                            ("Basketball", "Basketball"),
                            ("Running", "Running"),
                            ("Casual", "Casual"),
                            ("Lifestyle", "Lifestyle"),
                            ("Accessories", "Accessories"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Men", "Men"),
                            ("Women", "Women"),
                            ("Unisex", "Unisex"),
                        ],
                        max_length=10,
                    ),
                ),
                ("size", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=50)),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("Leather", "Leather"),
                            ("Canvas", "Canvas"),
                            ("Primeknit", "Primeknit"),
                            ("Mesh", "Mesh"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
