# Generated by Django 5.1.2 on 2025-03-16 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumpost",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="ForumPost",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
