# Generated by Django 5.1.2 on 2025-03-17 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_remove_forumpost_user_remove_notification_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LikedItem",
        ),
    ]
